spring:
  application:
    name: dungeon-game-kata
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb # 'db' = service name on docker-compose
    username: app
    password: secret

  sql:
    init:
      mode: always #
      continue-on-error: true

server:
  address: 0.0.0.0
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
